// DnsThreadNum()
// DnsThreadNumMax()
// DnsThreadNumMaxSet(constUINTnum)
// DnsResolve(IP*ipv6,IP*ipv4,constchar*hostname,UINTtimeout,volatileconstbool*cancel_flag)
// GetIPEx(IP*ip,constchar*hostname,UINTtimeout,volatileconstbool*cancel_flag)
